/**
 * Auto-generated by generate-media-list.js — do not edit by hand.
 * Add files to the media/ folder, then run: node generate-media-list.js
 */

window.mediaData = [
  {
    "url": "media/012B5EE1-1C52-4644-84E8-F1C84D4FB686.MOV",
    "type": "video"
  },
  {
    "url": "media/2B09B5CE-68A8-4F8E-91A3-0FB1C229ADFE.MOV",
    "type": "video"
  },
  {
    "url": "media/31641eb5-51e4-4489-a3b1-9443db7782f8.JPG",
    "type": "image"
  },
  {
    "url": "media/3400BF2F-5C50-4013-840D-E8919EE0974C.MP4",
    "type": "video"
  },
  {
    "url": "media/64643f63-a35e-4585-ad2d-efc98c9d43c9.JPG",
    "type": "image"
  },
  {
    "url": "media/69330dd6-0d31-4a18-9196-b07b5a4b7515.png",
    "type": "image"
  },
  {
    "url": "media/7AC10C49-8A23-4A2C-8281-5A4BCA7CB5B9.MOV",
    "type": "video"
  },
  {
    "url": "media/7CD5831A-0C56-477C-A04F-1903C601004C.mov",
    "type": "video"
  },
  {
    "url": "media/7a730dfd-f8b8-41ca-94a9-586e231d441e.png",
    "type": "image"
  },
  {
    "url": "media/80E6756F-9D76-4A67-9B34-4E3F3CEEBD10.MP4",
    "type": "video"
  },
  {
    "url": "media/8e484582-03d2-4a86-82fb-acb37b1838ad.png",
    "type": "image"
  },
  {
    "url": "media/9674503E-CCB9-41EC-BCB8-6E0EAB61E2CB.mov",
    "type": "video"
  },
  {
    "url": "media/BA9C257D-8571-4ECF-9F88-C97BD79C3A77.MOV",
    "type": "video"
  },
  {
    "url": "media/IMG_4623.jpeg",
    "type": "image"
  },
  {
    "url": "media/IMG_5083.jpeg",
    "type": "image"
  },
  {
    "url": "media/IMG_5084.jpeg",
    "type": "image"
  },
  {
    "url": "media/IMG_5235.JPG",
    "type": "image"
  },
  {
    "url": "media/IMG_7794.jpg",
    "type": "image"
  },
  {
    "url": "media/IMG_8020.JPG",
    "type": "image"
  },
  {
    "url": "media/aaf5441b-d863-4745-8ea0-6aa838e5d4bb.png",
    "type": "image"
  },
  {
    "url": "media/ca78dbe4-3da4-457e-9c69-5df514545629.JPG",
    "type": "image"
  },
  {
    "url": "media/cm-chat-media-video-1_4a8ead75-e60a-54d4-9146-94531ff5822c_32867_0_0.MOV",
    "type": "video"
  },
  {
    "url": "media/d759a7c5-6398-4a74-924b-bd920525d5ec.png",
    "type": "image"
  },
  {
    "url": "media/dfabbd0c-89ad-4f7b-a308-ec7e5c66c89f.JPG",
    "type": "image"
  }
];
